### PR TITLE
ENG-0000 - General Improvements

### PR DESCRIPTION
**Pull request by mcnielsen**
Supports activation of applications running in subdirectories.
Removes dead location properties.
Provides separate locaion ID for static content origin, allowing AlLocation.MagmaUI to be pointed dynamically at wherever it is being served from.

### CODE REVIEW

**Comment by mcnielsen** [comment]
test it

**Comment by mcnielsen** [comment]
test it

**Comment by mcnielsen** [comment]
test it

**Comment by mcnielsen** [comment]
test it

**Comment by mcnielsen** [comment]
test it

**Comment by mcnielsen** [comment]
test it

**Review by jmvalencia — APPROVED** [review]

**Pull request merged**
